[package]
name = "bidi-check-playground"
version = "0.1.0"
authors = ["Sergey Shepelev <temotor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arguably = "2"
ignore = "0.4"
